name: statsforecast
channels:
  - conda-forge
dependencies:
  - holidays<0.21 # zone info errors
  - jupyterlab
  - matplotlib
  - numba>=0.55.0
  - numpy>=1.21.6
  - pandas>=1.3.5
  - pyspark
  - pip
  - prophet
  - scipy>=1.7.3
  - statsmodels>=0.13.2
  - tabulate
  - plotly
  - pip:
    - nbdev
    - tqdm
    - plotly-resampler
    - fugue[dask,ray]
